name: LandRoutes

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          cache: maven
          java-version: 11
          distribution: 'adopt'
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests verify
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Analyze with SonarQube
        run: mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adrianrusu_land-routes -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Upload build files.
        uses: actions/upload-artifact@v1
        with:
          name: target
          path: target